[package]
name = "deno_cli_snapshots"
version = "0.19.0"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides snapshots for the deno CLI"
repository = "https://github.com/denoland/deno"
exclude = [
  "std/fs/testdata/0-link.ts",
  "std/fs/testdata/copy_dir_link_file/0.txt",
]

[lib]
path = "lib.rs"

[dependencies]
deno_typescript = { path = "../deno_typescript", version = "0.19.0" }

[dev-dependencies]
deno = { path = "../core", version = "0.19.0" }

[build-dependencies]
deno_typescript = { path = "../deno_typescript", version = "0.19.0" }

