# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_snapshots"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "v8 snapshot used by the Deno CLI"

[lib]
path = "lib.rs"

[features]
disable = []

[build-dependencies]
deno_runtime = { workspace = true, features = ["include_js_files_for_snapshotting", "only_snapshotted_js_sources", "snapshot"] }
