# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
version = "0.102.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
tokio.workspace = true
uuid.workspace = true
