# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
<<<<<<< HEAD
version = "0.117.0"
=======
version = "0.118.0"
>>>>>>> 118be11e8 (fix(runtime): snapshot options op missing during snapshot (#21235))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
tokio.workspace = true
uuid.workspace = true
