# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_broadcast_channel"
version = "0.216.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "DEPRECATED: Use deno_web instead"

[lib]
path = "lib.rs"
