# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_broadcast_channel"
version = "0.196.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
deno_error.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
