# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webidl"
version = "0.13.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "WebIDL implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.95.0", path = "../../core" }
