# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "node_resolver"
version = "0.10.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Node.js module resolution algorithm used in Deno"

[lib]
path = "lib.rs"

[features]
sync = ["deno_package_json/sync"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
deno_media_type.workspace = true
deno_package_json.workspace = true
deno_path_util.workspace = true
futures.workspace = true
lazy-regex.workspace = true
once_cell.workspace = true
path-clean = "=0.1.0"
regex.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
