# Copyright 2018-2026 the Deno authors. MIT license.

[package]
name = "libdeno_bindings"
version = "2.6.8"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Provides deno as a c library"

[lib]
path = "lib.rs"
doc = false
