[package]
name = "test_plugin"
version = "0.0.1"
authors = ["the deno authors"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
deno = { path = "../core" }
futures = "0.3"