# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_plugin"
version = "0.0.1"
license = "MIT"
authors = ["the deno authors"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.5"
deno_core = { path = "../core" }

[dev-dependencies]
test_util = { path = "../test_util" }
