# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_resolver"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Deno resolution algorithm"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
base32.workspace = true
deno_media_type.workspace = true
deno_package_json.workspace = true
deno_package_json.features = ["sync"]
deno_path_util.workspace = true
deno_semver.workspace = true
node_resolver.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
test_util.workspace = true
