# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_resolver"
version = "0.33.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Deno resolution algorithm"

[lib]
path = "lib.rs"

[features]
sync = ["dashmap", "deno_package_json/sync", "node_resolver/sync", "deno_config/sync", "deno_cache_dir/sync"]

[dependencies]
anyhow.workspace = true
async-once-cell.workspace = true
async-trait.workspace = true
base32.workspace = true
boxed_error.workspace = true
dashmap = { workspace = true, optional = true }
deno_cache_dir.workspace = true
deno_config.workspace = true
deno_error.workspace = true
deno_media_type.workspace = true
deno_npm.workspace = true
deno_package_json.workspace = true
deno_path_util.workspace = true
deno_semver.workspace = true
deno_terminal.workspace = true
futures.workspace = true
import_map.workspace = true
indexmap.workspace = true
log.workspace = true
node_resolver.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
sys_traits.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
sys_traits = { workspace = true, features = ["memory", "real", "serde_json"] }
test_util.workspace = true
