# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
version = "0.13.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "URL API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.95.0", path = "../../core" }
idna = "0.2.3"
percent-encoding = "2.1.0"
serde = { version = "1.0.126", features = ["derive"] }

[dev-dependencies]
deno_bench_util = { version = "0.7.0", path = "../../bench_util" }
deno_webidl = { version = "0.13.0", path = "../webidl" }

[[bench]]
name = "url_ops"
harness = false
