# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_kv"
<<<<<<< HEAD
version = "0.16.0"
=======
version = "0.17.0"
>>>>>>> ef24d1a0b (1.34.3 (#19525))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno database API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
deno_core.workspace = true
hex.workspace = true
num-bigint.workspace = true
rand.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
