# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_kv"
version = "0.26.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno database API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
deno_core.workspace = true
deno_unsync = "0.1.1"
hex.workspace = true
log.workspace = true
num-bigint.workspace = true
prost.workspace = true
rand.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["serde"] }
termcolor = "1.1.3"

[build-dependencies]
prost-build.workspace = true
