# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.16.1"
edition = "2018"
description = "Web Cryptography API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.83.0", path = "../../core" }
rand = "0.8.3"
ring = { version = "0.16.20", features = ["std"] }
rsa = "0.4.0"
sha-1 = "0.9.4"
sha2 = "0.9.3"
serde = { version = "1.0.123", features = ["derive"] }
tokio = { version = "1.2.0", features = ["full"] }

