# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.13.1"
edition = "2018"
description = "Collection of WebCrypto APIs"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.80.0", path = "../../core" }
rand = "0.8.3"

