# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.14.0"
edition = "2018"
description = "Collection of WebCrypto APIs"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.80.1", path = "../../core" }
rand = "0.7.0"
ring = { version = "0.16.20", features = ["std"] }
rsa = { git = "https://github.com/RustCrypto/RSA", rev = "616b08d" }
sha-1 = "0.9.4"
sha2 = "0.9.3"
serde = { version = "1.0.123", features = ["derive"] }
tokio = { version = "1.2.0", features = ["full"] }
