# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "napi_sym"
version = "0.101.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "proc macro for writing N-API symbols"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
