# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.158.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_permissions.workspace = true
dlopen2.workspace = true
dynasmrt = "1.2.3"
libffi = "=3.2.0"
libffi-sys = "=2.3.0"
log.workspace = true
serde.workspace = true
serde-value = "0.7"
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["errhandlingapi", "minwindef", "ntdef", "winbase", "winnt"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_aarch, values("x86_64", "aarch64"))'] }
