# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_ffi"
version = "0.189.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[dependencies]
cranelift.workspace = true
cranelift-native.workspace = true
deno_core.workspace = true
deno_error.workspace = true
deno_permissions.workspace = true
denort_helper.workspace = true
dlopen2.workspace = true
libffi.workspace = true
libffi-sys.workspace = true
log.workspace = true
memmap2.workspace = true
num-bigint.workspace = true
serde.workspace = true
serde-value.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["errhandlingapi", "minwindef", "ntdef", "winbase", "winnt"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_aarch, values("x86_64", "aarch64"))'] }
