# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.85.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
dlopen.workspace = true
dynasmrt = "1.2.3"
libffi = "3.1.0"
serde.workspace = true
serde-value = "0.7"
serde_json = "1.0"
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["errhandlingapi", "minwindef", "ntdef", "winbase", "winnt"] }
