# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.60.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.155.0", path = "../../core" }
dlopen = "0.1.8"
dynasmrt = "1.2.3"
libffi = "3.0.0"
serde = { version = "1.0.129", features = ["derive"] }
tokio = { version = "1.21", features = ["full"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["errhandlingapi", "minwindef", "ntdef", "winbase", "winnt"] }
