# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.95.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dependencies]
deno_core.workspace = true
dlopen.workspace = true
dynasmrt = "1.2.3"
libffi = "=3.2.0"
libffi-sys = "=2.2.1"
serde.workspace = true
serde-value = "0.7"
serde_json = "1.0"
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["errhandlingapi", "minwindef", "ntdef", "winbase", "winnt"] }
