# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fs"
version = "0.39.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Ops for interacting with the file system"

[lib]
path = "lib.rs"

[features]
sync_fs = []

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
deno_io.workspace = true
filetime.workspace = true
fs3.workspace = true
libc.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase"] }
