# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_fs"
version = "0.112.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Ops for interacting with the file system"

[lib]
path = "lib.rs"

[features]
sync_fs = []

[dependencies]
async-trait.workspace = true
base32.workspace = true
boxed_error.workspace = true
deno_core.workspace = true
deno_error.workspace = true
deno_io.workspace = true
deno_path_util.workspace = true
deno_permissions.workspace = true
filetime.workspace = true
libc.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["fs", "user"] }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase"] }
windows-sys.workspace = true
junction.workspace = true
