# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.44.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Collection of Web APIs"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1.50"
base64 = "0.13.0"
deno_core = { version = "0.95.0", path = "../../core" }
encoding_rs = "0.8.28"
serde = "1.0"
tokio = { version = "1.8.1", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }

[dev-dependencies]
futures = "0.3.15"
