# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.41.1"
edition = "2018"
description = "Collection of Web APIs"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
base64 = "0.13.0"
deno_core = { version = "0.92.0", path = "../../core" }
encoding_rs = "0.8.28"
serde = "1.0"
tokio = "1.7"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
futures = "0.3.15"
