# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_permissions"
version = "0.61.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Provides the deno permissions implementation."

[lib]
name = "deno_permissions"
path = "lib.rs"

[dependencies]
capacity_builder.workspace = true
deno_core.workspace = true
deno_error.workspace = true
deno_path_util.workspace = true
deno_terminal.workspace = true
fqdn.workspace = true
libc.workspace = true
log.workspace = true
once_cell.workspace = true
percent-encoding = { workspace = true, features = [] }
serde.workspace = true
thiserror.workspace = true
which.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["commapi", "knownfolders", "mswsock", "objbase", "psapi", "shlobj", "tlhelp32", "winbase", "winerror", "winuser", "winsock2", "processenv", "wincon", "wincontypes"] }
