# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
version = "0.112.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_permissions.workspace = true
libc.workspace = true
libloading = { version = "0.7" }
log.workspace = true
napi_sym.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
libuv-sys-lite = "=1.48.2"
