# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
<<<<<<< HEAD
version = "0.41.0"
=======
version = "0.42.0"
>>>>>>> 60fe8aa53 (1.35.2 (#19885))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
libloading = { version = "0.7" }
