# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
version = "0.12.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
libloading = { version = "0.7" }
