# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_geometry"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Geometry Interfaces Module API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
nalgebra.workspace = true
