# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_features"
version = "0.22.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Provides definitions of Deno unstable features."

[lib]
name = "deno_features"
path = "lib.rs"

[dependencies]
deno_core.workspace = true

[build-dependencies]
serde.workspace = true
serde_json.workspace = true
