# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.11.0"
edition = "2018"
description = "WebGPU implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.92.0", path = "../../core" }
tokio = { version = "1.7.1", features = ["full"] }
serde = { version = "1.0.125", features = ["derive"] }
wgpu-core = { version = "0.8.1", features = ["trace"] }
wgpu-types = "0.8.0"
