[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))']
rustflags = ["-L", "ext/image/dav1d/x86_64-unknown-linux-gnu"]

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))']
rustflags = ["-L", "ext/image/dav1d/aarch64-unknown-linux-gnu"]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "symbol-mangling-version=v0",
  "-L",
  "ext/image/dav1d/x86_64-pc-windows-msvc"
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-L",
  "ext/image/dav1d/aarch64-pc-windows-msvc"
]

[target.'cfg(all(windows, debug_assertions))']
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  # increase the stack size to prevent overflowing the
  # stack in debug when launching sub commands
  "link-arg=/STACK:4194304",
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C",
  "link-args=-weak_framework Metal -weak_framework MetalPerformanceShaders -weak_framework QuartzCore -weak_framework CoreGraphics",
  "-L",
  "ext/image/dav1d/x86_64-apple-darwin"
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C",
  "link-args=-fuse-ld=lld -weak_framework Metal -weak_framework MetalPerformanceShaders -weak_framework QuartzCore -weak_framework CoreGraphics",
  "-L",
  "ext/image/dav1d/aarch64-apple-darwin"
]

[target.'cfg(all())']
rustflags = [
  "-D",
  "clippy::all",
  "-D",
  "clippy::await_holding_refcell_ref",
  "-D",
  "clippy::missing_safety_doc",
  "-D",
  "clippy::undocumented_unsafe_blocks",
  "--cfg",
  "tokio_unstable",
]

# common environment variables for dav1d
[env]
SYSTEM_DEPS_DAV1D_LIB = "dav1d"
SYSTEM_DEPS_DAV1D_NO_PKG_CONFIG = "1"
