# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.28.0"
edition = "2018"
description = "Collection of Web APIs"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.77.0", path = "../../core" }
idna = "0.2.0"
serde = { version = "1.0.116", features = ["derive"] }

[dev-dependencies]
futures = "0.3.9"
