# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.1.0"
edition = "2018"
description = "provides webgpu Web API to deno_core"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.77.1", path = "../../core" }
serde = { version = "1.0.121", features = ["derive"] }
wgc = { package = "wgpu-core", version = "0.6.5" }
wgt = { package = "wgpu-types", version = "0.6.1" }
