# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
version = "0.5.0"
edition = "2018"
description = "Implementation of WebSocket API for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.79.0", path = "../../core" }
http = "0.2.3"
serde = { version = "1.0.123", features = ["derive"] }
tokio = { version = "1.2.0", features = ["full"] }
tokio-rustls = "0.22.0"
tokio-tungstenite = "0.13.0"
webpki = "0.21.4"
webpki-roots = "0.21.0"
