# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
version = "0.7.1"
edition = "2018"
description = "Implementation of WebSocket API for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.83.0", path = "../../core" }
http = "0.2.3"
serde = { version = "1.0.125", features = ["derive"] }
tokio = { version = "1.4.0", features = ["full"] }
tokio-rustls = "0.22.0"
tokio-tungstenite = { version = "0.14.0", features = ["rustls-tls"] }
webpki = "0.21.4"
webpki-roots = "0.21.1"
