# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_io"
version = "0.81.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "IO primitives for Deno extensions"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
filetime.workspace = true
fs3.workspace = true
log.workspace = true
once_cell.workspace = true
pin-project.workspace = true
tokio.workspace = true
uuid.workspace = true

[target.'cfg(not(windows))'.dependencies]
os_pipe.workspace = true
libc.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase", "processenv", "errhandlingapi"] }
rand.workspace = true
parking_lot.workspace = true
windows-sys.workspace = true
