# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_io"
version = "0.18.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "IO promitives for Deno extensions"

[lib]
path = "lib.rs"

[features]
# Enable to exclude JS sources from the binary (e.g. if they are already snapshotted).
exclude_js_sources = []
# Enable to override `exclude_js_sources` (e.g. for snapshot creation in `build.rs`).
force_include_js_sources = []

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
filetime.workspace = true
fs3.workspace = true
once_cell.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase", "processenv"] }
