# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_net"
version = "0.4.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Networking for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.95.0", path = "../../core" }

lazy_static = "1.4.0"
log = "0.4.14"
rustls = "0.19.0"
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "1.8.1", features = ["full"] }
trust-dns-proto = "0.20.3"
trust-dns-resolver = { version = "0.20.3", features = ["tokio-runtime", "serde-config"] }
webpki = "0.21.4"
webpki-roots = "0.21.1"
