# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_bench_util"
version = "0.57.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
publish = true
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Bench and profiling utilities for deno crates"

[lib]
path = "lib.rs"

[dependencies]
bencher = "0.1"
deno_core = { version = "0.145.0", path = "../core" }
once_cell = "1.10.0"
tokio = { version = "1.19", features = ["full"] }

[[bench]]
name = "op_baseline"
harness = false

[[bench]]
name = "utf8"
harness = false
