# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[package]
name = "bench_util"
version = "0.0.0"
authors = ["the Deno authors"]
edition = "2018"
description = "Bench and profiling utilities for deno crates"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1"
deno_core = { version = "0.84.0", path = "../core" }
tokio = { version = "1.4.0", features = ["full"] }
