# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_bench_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
description = "Bench and profiling utilities for deno crates"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1"
deno_core = { version = "0.88.0", path = "../core" }
tokio = { version = "1.6.0", features = ["full"] }

[[bench]]
name = "op_baseline"
harness = false
