# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.18.0"
edition = "2018"
description = "provides fetch Web API to deno_core"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
bytes = "1.0.1"
deno_core = { version = "0.75.0", path = "../../core" }
reqwest = { version = "0.11.0", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1.0.116", features = ["derive"] }
tokio = { version = "1.0.1", features = ["full"] }
tokio-stream = "0.1.1"
tokio-util = "0.6.0"
