# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.16.0"
edition = "2018"
description = "provides fetch Web API to deno_core"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.73.0", path = "../../core" }
reqwest = { version = "0.10.8", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1.0.116", features = ["derive"] }
tokio-compat-02 = "0.1.2"
