# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_webidl"
version = "0.202.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "WebIDL implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

[dev-dependencies]
deno_bench_util.workspace = true

[[bench]]
name = "dict"
harness = false
