variables:
  DENO_VERSION: "v0.19.0"
  TS_VERSION: "3.4.5"
  ESLINT_VERSION: "6.5.1"
  TS_ESLINT_VERSION: "2.3.2"

# TODO Try to get eslint to run under Deno, like prettier
jobs:
  - job: "Linux"
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: .ci/template.linux.yml

  - job: "Mac"
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: .ci/template.mac.yml

  - job: "Windows"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: .ci/template.windows.yml
