# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
version = "0.4.1"
edition = "2018"
description = "Implementation of BroadcastChannel API for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1"
deno_core = { version = "0.92.0", path = "../../core" }
tokio = { version = "1.8.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
