# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "napi_sym"
version = "0.132.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "proc macro for writing N-API symbols"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
