# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
version = "0.158.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_native_certs = "0.3.0"
rustls.workspace = true
rustls-pemfile.workspace = true
rustls-tokio-stream.workspace = true
rustls-webpki.workspace = true
serde.workspace = true
tokio.workspace = true
webpki-roots.workspace = true
