# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
version = "0.1.1"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.96.0", path = "../../core" }
lazy_static = "1.4.0"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
rustls = { version = "0.19.1", features = ["dangerous_configuration"] }
rustls-native-certs = "0.5.0"
serde = { version = "1.0.126", features = ["derive"] }
webpki = "0.21.4"
webpki-roots = "0.21.1"
