# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
version = "0.16.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.111.0", path = "../../core" }
once_cell = "=1.9.0"
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6.1"
rustls-pemfile = "0.2.1"
serde = { version = "1.0.129", features = ["derive"] }
webpki = "0.22"
webpki-roots = "0.22"
