[package]
name = "deno_ops"
version = "0.38.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Proc macro for writing Deno Ops"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
once_cell = "1.10.0"
pmutil = "0.5.3"
proc-macro-crate = "1.1.3"
proc-macro2 = "1"
quote = "1"
regex = "1.6.0"
syn = { version = "1", features = ["full", "extra-traits"] }

[dev-dependencies]
deno_core = { path = "../core" }
prettyplease = "0.1.21"
testing_macros = "0.2.7"
trybuild = "1.0.61"
