# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ops"
version = "0.39.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Proc macro for writing Deno Ops"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
once_cell.workspace = true
pmutil = "0.5.3"
proc-macro-crate = "1.1.3"
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true

[dev-dependencies]
prettyplease = "0.1.21"
testing_macros = "0.2.7"
trybuild = "1.0.71"
