[package]
name = "deno-hash"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
repository = "https://github.com/denoland/deno"

[lib]
crate-type = ["cdylib"]

[dependencies]
digest = "0.8.1"
md2 = "0.8"
md4 = "0.8"
md-5 = "0.8"
ripemd160 = "0.8.0"
ripemd320 = "0.8.0"
sha-1 = "0.8.2"
sha2 = "0.8.2"
sha3 = "0.8.2"
wasm-bindgen = "0.2.63"

[profile.release]
lto = true
opt-level = 3
