# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
version = "0.7.0"
edition = "2018"
description = "Implementation of WebStorage API for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.94.0", path = "../../core" }
deno_web = { version = "0.43.0", path = "../web" }
rusqlite = { version = "0.25.3", features = ["unlock_notify", "bundled"] }
serde = { version = "1.0.126", features = ["derive"] }
