# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_cron"
version = "0.82.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno cron API"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["now"] }
deno_core.workspace = true
deno_error.workspace = true
saffron.workspace = true
thiserror.workspace = true
tokio.workspace = true
