# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_cron"
version = "0.51.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of the Deno cron API"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono = { workspace = true, features = ["now"] }
deno_core.workspace = true
saffron.workspace = true
tokio.workspace = true
