# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webidl"
version = "0.3.0"
edition = "2018"
description = "WebIDL implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.84.0", path = "../../core" }
